# Generated by Django 4.0.2 on 2022-04-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='id_pr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
